before_all do
	puts ENV['owner'] = "jacobrharris"
	puts ENV['github_owner'] = "jacobrharris"
	puts ENV['github_repository'] = "JHDataUtils"
	puts ENV['api_token'] = "c30d1acc09b6608c51d4468d132185dc34bfabbf"
end

lane :build do
	import_from_git(
	  url: 'https://github.com/AFNetworking/fastlane.git', 
	  branch: '0.0.2'
	)

	complete_framework_release(
		skip_ci_check:true
	)
end

